# Generated by Django 5.1.1 on 2024-11-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("nickname", models.CharField(max_length=30, unique=True)),
                ("prefer", models.CharField(blank=True, max_length=100, null=True)),
                ("interest", models.CharField(blank=True, max_length=100, null=True)),
                ("job", models.CharField(blank=True, max_length=100, null=True)),
                ("env", models.CharField(blank=True, max_length=100, null=True)),
                ("budget", models.IntegerField(blank=True, null=True)),
                ("fam", models.IntegerField(blank=True, null=True)),
                (
                    "result_area",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
