# Generated by Django 5.1.1 on 2024-11-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post_content",
            name="like_num",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="post_content",
            name="scrap_num",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
