# Generated by Django 5.1.1 on 2024-11-21 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Custom_group",
            fields=[
                ("group_id", models.AutoField(primary_key=True, serialize=False)),
                ("constructor", models.CharField(max_length=30)),
                ("image", models.ImageField(upload_to="group_images/")),
                ("group_name", models.CharField(max_length=30)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tags", models.CharField(max_length=30)),
                (
                    "group_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="networking.custom_group",
                    ),
                ),
            ],
        ),
    ]
