# Generated by Django 5.1.1 on 2024-11-21 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("networking", "0002_tag_delete_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="tags",
            new_name="tag",
        ),
    ]
