# Generated by Django 5.1.1 on 2024-11-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networking", "0003_rename_tags_tag_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="group_id",
        ),
        migrations.AddField(
            model_name="tag",
            name="group_name",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
